import { GetCommandStatusCommand } from './get-command-status-command.js';
import { ListCommandsCommand } from './list-commands-command.js';
import { ListSessionsCommand } from './list-sessions-command.js';
import { ReadCommandLogsCommand } from './read-command-logs-command.js';
import { CommandRegistry } from './registry.js';
import { RestartCommandCommand } from './restart-command-command.js';
import { RunSstCommand } from './run-sst-command.js';
import { StartCommand } from './start-command.js';
import { StartSstCommandCommand } from './start-sst-command-command.js';
import { StopCommand } from './stop-command.js';
import { StopSstCommandCommand } from './stop-sst-command-command.js';
import { VersionCommand } from './version-command.js';
import { WaitForNextReadyCommand } from './wait-for-next-ready-command.js';
import { WaitForReadyCommand } from './wait-for-ready-command.js';

export { Command, type CliContext } from './command.js';
export { CommandRegistry } from './registry.js';
export { VersionCommand } from './version-command.js';
export { StartCommand } from './start-command.js';
export { StopCommand } from './stop-command.js';
export { ListSessionsCommand } from './list-sessions-command.js';
export { WaitForReadyCommand } from './wait-for-ready-command.js';
export { WaitForNextReadyCommand } from './wait-for-next-ready-command.js';
export { ListCommandsCommand } from './list-commands-command.js';
export { GetCommandStatusCommand } from './get-command-status-command.js';
export { ReadCommandLogsCommand } from './read-command-logs-command.js';
export { StartSstCommandCommand } from './start-sst-command-command.js';
export { StopSstCommandCommand } from './stop-sst-command-command.js';
export { RestartCommandCommand } from './restart-command-command.js';
export { RunSstCommand } from './run-sst-command.js';

export const defaultRegistry = (): CommandRegistry => {
  const registry = new CommandRegistry();
  registry.register(new VersionCommand());
  registry.register(new StartCommand());
  registry.register(new StopCommand());
  registry.register(new ListSessionsCommand());
  registry.register(new WaitForReadyCommand());
  registry.register(new WaitForNextReadyCommand());
  registry.register(new ListCommandsCommand());
  registry.register(new GetCommandStatusCommand());
  registry.register(new ReadCommandLogsCommand());
  registry.register(new StartSstCommandCommand());
  registry.register(new StopSstCommandCommand());
  registry.register(new RestartCommandCommand());
  registry.register(new RunSstCommand());
  return registry;
};
